run-shell "echo 'Loading ~/.tmux.conf'"

#Enable Mouse
set -g mouse on

#Enable colors
set -g default-terminal "screen-256color"

#Copy and Paste
set -g set-clipboard external

#Enable vi mode
set-window-option -g mode-keys vi

#Terminal Scrollback
set -g history-limit 50000

#Set Default Shell
set -g default-shell /bin/zsh

#Set prefix
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# New window and retain cwd
bind-key c new-window -c "#{pane_current_path}"

#Switching Windows
bind-key n next-window
bind-key p previous-window

# Easy reload config
bind-key r source-file ~/.tmux.conf \; run-shell "echo 'Reloaded tmux configuration'"

#list key bindings
unbind-key ?
bind-key ? list-keys -N

#Enable Mouse Dragging
unbind -T copy-mode-vi MouseDragEnd1Pane

#Splitting window
bind-key = split-window -h -c "#{pane_current_path}"
bind-key ] split-window -v -c "#{pane_current_path}"
unbind-key '"'
unbind-key %

# hjkl pane traversal
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

#Copy pasta
unbind-key p
bind-key P paste-buffer
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
bind-key -T copy-mode-vi 'r' send -X rectangle-toggle

#Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'


#dracula
# available plugins: battery, cpu-usage, git, gpu-usage, ram-usage, tmux-ram-usage, network, network-bandwidth, network-ping, ssh-session, attached-clients, network-vpn, weather, time, mpc, spotify-tui, playerctl, kubernetes-context, synchronize-panes
set -g @dracula-plugins "battery time weather"
set -g @dracula-show-flags true
set -g @dracula-show-powerline true

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
